import { HttpStatus } from '@nestjs/common';

export const ErrorHttpStatusMap: Record<string, HttpStatus> = {
  // Auth
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  REFRESH_TOKEN_REVOKED: HttpStatus.UNAUTHORIZED,
  EMAIL_NOT_VERIFIED: HttpStatus.UNAUTHORIZED,
  TWO_FACTOR_REQUIRED: HttpStatus.UNAUTHORIZED,
  OTP_FAILED_ATTEMPTS: HttpStatus.UNAUTHORIZED,
  TWO_FACTOR_NOT_ENABLED: HttpStatus.UNAUTHORIZED,
  INVALID_REAUTH_TOKEN: HttpStatus.UNAUTHORIZED,
  INVALID_REFRESH_TOKEN: HttpStatus.UNAUTHORIZED,
  TWO_FACTOR_ALREADY_ENABLED: HttpStatus.FORBIDDEN,
  TWO_FACTOR_SMS_DISABLED: HttpStatus.FORBIDDEN,
  TWO_FACTOR_TYPE_INVALID: HttpStatus.FORBIDDEN,
  TWO_FACTOR_CODE_INVALID: HttpStatus.FORBIDDEN,
  REAUTH_TOKEN_NOT_FOUND: HttpStatus.FORBIDDEN,

  // OAuth
  OAUTH_LOGIN_REQUIRED: HttpStatus.UNAUTHORIZED,
  OAUTH_PROVIDER_NOT_FOUND: HttpStatus.NOT_FOUND,
  OAUTH_PROVIDER_DISABLED: HttpStatus.FORBIDDEN,
  OAUTH_PROVIDER_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

  // Users
  USER_NOT_FOUND: HttpStatus.NOT_FOUND,
  USER_DISABLED: HttpStatus.FORBIDDEN,
  EMAIL_ALREADY_EXISTS: HttpStatus.CONFLICT,
  USER_ALREADY_EXISTS: HttpStatus.CONFLICT,
  ROL_NOT_FOUND: HttpStatus.NOT_FOUND,
  USER_HAS_CREDENTIALS: HttpStatus.CONFLICT,
  DOCUMENT_EXISTS: HttpStatus.CONFLICT,
  INVALID_PASSWORD: HttpStatus.UNAUTHORIZED,
  PENDING_USER: HttpStatus.FORBIDDEN,
  SUSPENDED_USER: HttpStatus.FORBIDDEN,
  INACTIVE_USER: HttpStatus.FORBIDDEN,

  // Credentials
  PASSWORDS_DOES_NOT_MATCH: HttpStatus.FORBIDDEN,

  // Tokens
  TOKEN_EXPIRED: HttpStatus.UNAUTHORIZED,
  TOKEN_INVALID: HttpStatus.UNAUTHORIZED,
  TOKEN_NOT_FOUND: HttpStatus.NOT_FOUND,
  TOKEN_REVOKED: HttpStatus.UNAUTHORIZED,

  // Permissions
  FORBIDDEN_ACTION: HttpStatus.FORBIDDEN,
  INSUFFICIENT_PERMISSIONS: HttpStatus.FORBIDDEN,
  ROLE_NOT_ASSIGNED: HttpStatus.FORBIDDEN,

  // Security
  RATE_LIMIT_EXCEEDED: HttpStatus.TOO_MANY_REQUESTS,
  ACCOUNT_LOCKED: HttpStatus.FORBIDDEN,
  PASSWORD_EXPIRED: HttpStatus.FORBIDDEN,
  BRUTE_FORCE_BLOCKED: HttpStatus.TOO_MANY_REQUESTS,

  // System
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  DATABASE_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

  // Identity Types
  IDENTITY_TYPE_NOT_FOUND: HttpStatus.NOT_FOUND,

  // Common
  INVALID_STATE: HttpStatus.BAD_REQUEST,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  INTERNAL_SERVER_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  BAD_GATEWAY: HttpStatus.BAD_GATEWAY,
  GATEWAY_TIMEOUT: HttpStatus.GATEWAY_TIMEOUT,
  HTTP_VERSION_NOT_SUPPORTED: HttpStatus.HTTP_VERSION_NOT_SUPPORTED,
  BAD_REQUEST: HttpStatus.BAD_REQUEST,
};
