export enum SecurityError {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
  BRUTE_FORCE_BLOCKED = 'BRUTE_FORCE_BLOCKED',
}
